name: cs329x
channels:
  - conda-forge
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - anyio=4.11.0=pyhcf101f3_0
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - aws-c-auth=0.9.1=h8818502_7
  - aws-c-cal=0.9.10=hca30140_1
  - aws-c-common=0.12.5=hc919400_1
  - aws-c-compression=0.3.1=h61d5560_8
  - aws-c-event-stream=0.5.6=h18584fc_6
  - aws-c-http=0.10.7=hcd69b29_4
  - aws-c-io=0.23.3=h9710c81_3
  - aws-c-mqtt=0.13.3=ha255ef3_10
  - aws-c-s3=0.10.1=hd860258_2
  - aws-c-sdkutils=0.2.4=h61d5560_3
  - aws-checksums=0.2.7=h61d5560_4
  - aws-crt-cpp=0.35.2=h5596a46_4
  - aws-sdk-cpp=1.11.606=h95becb6_7
  - azure-core-cpp=1.16.1=h88fedcc_0
  - azure-identity-cpp=1.13.2=h853621b_1
  - azure-storage-blobs-cpp=12.15.0=h10d327b_1
  - azure-storage-common-cpp=12.11.0=h7e4aa5d_1
  - azure-storage-files-datalake-cpp=12.13.0=hb288d13_1
  - brotli=1.2.0=hca488c2_0
  - brotli-bin=1.2.0=hce9b42c_0
  - brotli-python=1.2.0=py313h79bbab8_0
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - cffi=2.0.0=py313h224173a_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py313ha61f8ec_3
  - cpython=3.13.9=py313hd8ed1ab_101
  - cycler=0.12.1=pyhd8ed1ab_1
  - dataclasses=0.8=pyhc8e2a94_3
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=hda038a8_0
  - debugpy=1.8.17=py313hc37fe24_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - ffmpeg=8.0.0=gpl_h670d5b4_106
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py313h7d74516_0
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - gdk-pixbuf=2.44.4=h7542897_0
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - glog=0.7.1=heb240a5_0
  - glslang=16.0.0=h60b4770_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py313hc1c22ca_2
  - graphite2=1.3.14=hec049ff_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=haf38c7b_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kaldi=5.5.1172=cpu_h0f61937_2
  - kiwisolver=1.4.9=py313h7add70c_2
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libarrow=22.0.0=h4a3aeba_4_cpu
  - libarrow-acero=22.0.0=hc317990_4_cpu
  - libarrow-compute=22.0.0=h75845d1_4_cpu
  - libarrow-dataset=22.0.0=hc317990_4_cpu
  - libarrow-substrait=22.0.0=h144af7f_4_cpu
  - libass=0.17.4=hcbd7ca7_0
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.9.0=38_h51639a9_openblas
  - libbrotlicommon=1.2.0=h87ba0bc_0
  - libbrotlidec=1.2.0=h95a88de_0
  - libbrotlienc=1.2.0=hb1b9735_0
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=21.1.4=hf598326_0
  - libde265=1.0.15=h2ffa867_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.86.2=hfe11c1f_1
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libheif=1.19.7=gpl_h79e6334_100
  - libhwloc=2.12.1=default_h48b22c3_1002
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.9.0=38_hd9741b5_openblas
  - liblapacke=3.9.0=38_h1b118fd_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libnghttp2=1.67.0=hc438710_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libopenvino=2025.2.0=h56e7ac4_1
  - libopenvino-arm-cpu-plugin=2025.2.0=h56e7ac4_1
  - libopenvino-auto-batch-plugin=2025.2.0=he81eb65_1
  - libopenvino-auto-plugin=2025.2.0=he81eb65_1
  - libopenvino-hetero-plugin=2025.2.0=h273c05f_1
  - libopenvino-ir-frontend=2025.2.0=h273c05f_1
  - libopenvino-onnx-frontend=2025.2.0=h6386500_1
  - libopenvino-paddle-frontend=2025.2.0=h6386500_1
  - libopenvino-pytorch-frontend=2025.2.0=hec049ff_1
  - libopenvino-tensorflow-frontend=2025.2.0=hee62d61_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hec049ff_1
  - libopus=1.5.2=h48c0fde_0
  - libparquet=22.0.0=h0ac143b_4_cpu
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.11.05=h91c62da_0
  - librsvg=2.60.0=h5c55ec3_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.4=h4237e3c_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.1=h4030677_1
  - libtorch=2.8.0=cpu_generic_hf67e7d3_2
  - libusb=1.0.29=hbc156a2_0
  - libutf8proc=2.11.2=hd2415e0_0
  - libuv=1.51.0=h6caf38d_1
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.14.1=h7bae524_0
  - libvulkan-loader=1.4.328.1=h49c215f_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.5=h4a912ad_0
  - lz4-c=1.10.0=h286801f_1
  - markupsafe=3.0.3=py313h7d74516_0
  - matplotlib=3.10.7=py313h39782a4_0
  - matplotlib-base=3.10.7=py313h58042b9_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=h248ca61_1
  - nltk=3.9.2=pyhcf101f3_1
  - nomkl=1.0=h5ca1d4c_0
  - numpy=2.3.5=py313h9771d21_0
  - openfst=1.8.4=ha393de7_1
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - optree=0.18.0=py313ha61f8ec_0
  - orc=2.2.1=h4fd0076_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313h7d16b84_1
  - pango=1.56.4=h875632e_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.47=h30297fc_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh145f28c_0
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.2=py313h9734d34_1
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=hd3d436d_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow-core=22.0.0=py313hb9a0e51_0_cpu
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.9=hfc2f54d_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.13.9=h4df99d1_101
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py313hee11f83_1
  - python_abi=3.13=8_cp313
  - pytorch=2.8.0=cpu_generic_py313_h1ee2325_2
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py313h7d74516_0
  - pyzmq=27.1.0=py312hd65ceae_0
  - qhull=2020.2=h420ef59_5
  - rav1e=0.7.1=h0716509_3
  - re2=2025.11.05=h64b956e_0
  - readline=8.2=h1d1bf99_2
  - requests=2.32.5=pyhd8ed1ab_0
  - sdl2=2.32.56=h248ca61_0
  - sdl3=3.2.26=h919df07_0
  - shaderc=2025.4=h1a5098f_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - spirv-tools=2025.4=ha7d2532_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.1.2=h12ba402_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=h66ce52b_1
  - tk=8.6.13=h892fb3f_2
  - tokenizers=0.22.1=py313h4bd1e59_1
  - torchaudio=2.8.0=cpu_py313h8c76682_2
  - torchcodec=0.8.1=cpu_py313_h006b54a_2
  - torchvision=0.24.0=cpu_py313_hacf4a80_2
  - torchvision-extra-decoders=0.0.2=py313hfccfda9_4
  - tornado=6.5.2=py313hcdf3177_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xxhash=0.8.3=haa4e116_0
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.2.5=h3470cca_0
  - zstandard=0.25.0=py313h9734d34_1
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - aioboto3==15.4.0
      - aiobotocore==2.25.0
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aioitertools==0.12.0
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.13.2
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - black==25.11.0
      - blobfile==3.1.0
      - boto3==1.40.49
      - botocore==1.40.49
      - certifi==2025.10.5
      - chess==1.11.2
      - chz==0.3.0
      - datasets==4.3.0
      - distro==1.9.0
      - docstring-parser==0.17.0
      - eval-type-backport==0.2.2
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - hf-xet==1.2.0
      - ijson==3.4.0.post0
      - inspect-ai==0.3.143
      - jiter==0.11.1
      - jmespath==1.0.1
      - jsonlines==4.0.0
      - jsonpatch==1.33
      - jsonpath-ng==1.7.0
      - jsonpointer==3.0.0
      - jsonref==1.1.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - latex2sympy2-extended==1.10.2
      - linkify-it-py==2.0.3
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - math-verify==0.8.0
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - mmh3==5.2.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - networkx==3.5
      - openai==2.6.1
      - pathlib-abc==0.5.2
      - pathspec==0.12.1
      - pillow==11.3.0
      - ply==3.11
      - propcache==0.4.1
      - protobuf==6.33.0
      - pyarrow==22.0.0
      - pycryptodomex==3.23.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pylatexenc==2.10
      - python-dotenv==1.2.1
      - pytokens==0.3.0
      - referencing==0.37.0
      - regex==2025.10.23
      - rich==14.2.0
      - rpds-py==0.28.0
      - s3fs==2025.9.0
      - s3transfer==0.14.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - semver==3.0.4
      - sentence-transformers==5.1.2
      - sentry-sdk==2.43.0
      - setuptools==80.9.0
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - smmap==5.0.2
      - soupsieve==2.8
      - tabulate==0.9.0
      - tenacity==9.1.2
      - termcolor==3.2.0
      - textarena==0.7.4
      - textual==6.4.0
      - threadpoolctl==3.6.0
      - tinker==0.2.2
      - tinker-cookbook==0.1.0
      - together==1.5.31
      - torch==2.9.0
      - transformers==4.57.1
      - typer==0.19.2
      - typing-inspection==0.4.2
      - uc-micro-py==1.0.3
      - universal-pathlib==0.3.4
      - wandb==0.22.3
      - websockets==15.0.1
      - wrapt==1.17.3
      - yarl==1.22.0
prefix: /Users/abhinavsattiraju/miniforge/envs/cs329x
